日本の祝日一覧情報をJSONのほか, CSVでも出力するよう修正
holidays-jp/generator pull request #1
Opened 2017-02-03 10:59 UTC by naokwn

データ生成コード, テストコードを修正
fixed both data generating code and test code.

2017-02-06 08:52 UTC, matsuoshi requested changes
すいません！
CSV出力形式に関して、さきほどお話した感じでご対応をお願いいたします！ 🙇

2017-02-06 08:52 UTC, matsuoshi commented on app/holidaysJP.php
> +    protected function output_csv_file($filename, $data)
こちら、仕様を明確に決めきれておらず、すみませんでした
CSVの出力形式ですが、以下のようなパターンでお願いできますでしょうか？ 👏 

```
2016-01-01,元日
2016-01-11,成人の日
2016-02-11,建国記念の日
```

(それによってテストも変更必要になるかと思います、お手数おかけしてすみません…！)

2017-02-06 08:52 UTC, matsuoshi commented on tests/holidaysJPTest.php
> +                $data[$date] = $dateTextArr[1][$key];
細かい指摘になりますが、 `$dateTextArr` と `$data` が初期化されていないので、場合によっては未定義のまま参照されるケースがあるかと思います、
空の配列としての初期化をお願いします

2017-02-07 01:47 UTC, naokwn commented
修正を加えました。ご確認をお願いします。

2017-02-07 04:59 UTC, matsuoshi reviewed
対応ありがとうございます、
動作自体はこれで問題ないと思います！

2点、コードの書き方のところでコメントさせてもらっています。修正必須ではなく、僕ならこう書くかな？といったレベルのものです、よければご確認くださいー

2017-02-07 04:59 UTC, matsuoshi commented on app/holidaysJP.php
> +        $recordArr = array_chunk($wholeRecord, 2);
一時変数 $wholeRecord と `array_chunk` 使われていますが、ここはシンプルに
ループ内に

```
$recordArr[] = [$date, $text]
```

でよいのかな、と思いました(どうでしょう？)

2017-02-07 04:59 UTC, matsuoshi commented on tests/holidaysJPTest.php
> +            }
95〜99行目で foreach を2回使われていますが、foreach を 1つにして、
`str_getcsv()` の結果を同じループ内で $data に入れたほうがコードとしては
短くなるかなと思いました。(こちらも、どうでしょう？)

2017-02-07 05:51 UTC, naokwn commented on app/holidaysJP.php
> +        $recordArr = array_chunk($wholeRecord, 2);
確かにそれでいいと思います。その方が綺麗ですので修正します。

2017-02-07 06:07 UTC, naokwn commented
冗長な処理を整理しました。テストパスすることも確認しました。

2017-02-07 07:06 UTC, merged

2017-02-07 07:07 UTC, matsuoshi commented
こちらで問題ないと思います、ご対応ありがとうございました！！ @naokwn